### ISSUE TITLE
Fatal error when installing keystone

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-idm-deprecated#1]
Hi,

I'm updating Keyrock to test the new version with our Fiware project (https://github.com/Bitergia/fiware-chanchan).  So far, it's been really easy to install and use, but since yesterday (27/05/2015) keystone fails to install with the following error:

```
Fatal error: local() encountered an error (return code 1) while executing 'sudo python tools/install_venv.py'
```

I've posted the full log here: https://gist.github.com/dmabtrg/b99e66af0376cad1d7ca

From the log, it seems there's some kind of version conflict for oslo.utils:

```
error: oslo.utils 1.2.1 is installed but oslo.utils<1.5.0,>=1.4.0 is required by set(['keystonemiddleware'])
Command "/opt/fi-ware-idm/keystone/.venv/bin/python setup.py develop" failed.
```

I'm no python expert, so I'm a bit in the dark here.  Our testing environment is Ubuntu 14.04.2 LTS and the install process was working fine two days ago.

Any help would be appreciated.
Thanks in advance.

**Comment by garcianavalon** [comment]
Hi,

I thought I had fixed that issue last week in https://github.com/ging/keystone/commit/89ec7210d3d98ae7858a50fac0aec69319f00266

Maybe it is a different external library now that has been updated and conflicts with our requirements. I'll take a look and try to figure out which ones are conflicting.

Thanks for your feedback,
Cheers.

**Comment by garcianavalon** [comment]
Hi,
I've pushed a patch to the keystone repo that should fix this issue https://github.com/ging/keystone/commit/dcadbc532041200860d608f6d146aadaf6f1b78e . I have tried installing the venv in a fresh clone from the repo and worked correctly.

I hope everything works now, let me know if it doesn't.
Cheers.

**Comment by dmabtrg** [comment]
I've tried again and it's working now.

Thank you. :-)
