### ISSUE TITLE
Changing password crashes KeyRock instance

### ISSUE THREAD

**Issue by redss** [ging/fiware-idm-deprecated#10]
Hello,

I've installed KeyRock on an Ubuntu 14.04 VM, using this [walkthrough](https://github.com/ging/fi-ware-idm/wiki/Installation-guide). After gaining access to settings menu, using fix from #6, I tried to change user's password. After doing so, I was logged out. However, when I tried to log in again using new credentials, I got 401 (unauthorized) error. Moreover, when I went back to the main page, I got 401 again. Clearing cookies helped, but situation was identical when I tried to log in again, no matter on what account. Passing invalid credentials did not break the application.

The only thing that can fix this situation is clearing the database with `fab keystone.database_reset` task. However, after changing a password, the application is broken again.

Details of the error: http://dpaste.com/0MSJATZ

Thanks in advance!

**Comment by garcianavalon** [comment]
Hi,

I don't know what could be happening, never had an issue with the passwords. Right now I'm out of the office, next week I can take a closer look to see what could be going wrong. Try checking the user table in the database, mainly the active/valid column. If you find out anything else please let me know.

Cheers,
Enrique

**Comment by vladanminic** [comment]
I have the same problem as redds. After changing password for idm user, KeyRock crashes.

---

edit:

I changed password in openstack_dashboard/local/local_settings.py as well and restarted Horizon, and now everything is working OK, idm user (with changed password) as well as other users with changed password.

**Comment by garcianavalon** [comment]
Hi,

I've tried changing my user's password and it works fine. Basing on @vladanminic's answer, looks like you changed the 'idm' account password, which is the one that the front-end uses to operate in the back-end. Update your settings with the new password and it should work fine.

Best regards,
Enrique
