### ISSUE TITLE
That Key Rock does not support Social Logins 100%. This should be really fixed asap.

### ISSUE THREAD

**Issue by IAIS4EP** [ging/fiware-idm-deprecated#11]

**Comment by garcianavalon** [comment]
Dear IAIS4EP,

Could you give me more details on the issue? What features are missing? Currently KeyRock supports all four grant types from the OAuth 2.0 protocol (plus the Refresh Token grant).

Thank you for your feedback.
Best regards,
Enrique

**Comment by garcianavalon** [comment]
Dear @IAIS4EP,

I'm closing this issue as no extra info is provided and, to my knowledge, all social features from the specification are supported. If you have more info on this topic, feel free to reopen this issue or a new one.

Best regards,
Enrique
