### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by marcinbudny** [ging/fiware-idm-deprecated#14]
Hello,

I can see there is a Dockerfile present in the repository. However this seems to be work in progress (as of commit 01c6d69099067a5c7ccc6050e2419437ae5ccd91). We are very much interested in deploying the Keyrock IdM from Docker. When do you plan to complete this task?

**Comment by garcianavalon** [comment]
Hi,

Docker support is a high priority task right now and it will be ready before the end of this month, most probably by the end of this week.

Best regards,
Enrique
