### ISSUE TITLE
Fiware-idm Dockerfile

### ISSUE THREAD

**Issue by albertinisg** [ging/fiware-idm-deprecated#15]
Hi!

I've seen you've started creating Dockerfiles for the `fiware-idm`. I just wanted to point that we've made already an initial effort to create a `fiware-idm` image and maybe it could help :)

The image is available in our [Github Repository](https://github.com/Bitergia/fiware-chanchan-docker/tree/master/images/idm-keyrock) and also in [Dockerhub](https://hub.docker.com/r/bitergia/idm-keyrock/).

As it's true that our image is designed more for integrating components, the main `Dockerfile` installs `fiware-idm` as stands in the documentation.

We've thought this design in order to use it together with [docker-compose](https://docs.docker.com/compose/) and to be used together (at least) with [Authzforce](http://catalogue.fiware.org/enablers/authorization-pdp-authzforce). So, apart from the image itself, we've added few features for integration like:
- Uncoupled users, roles, and permissions by adding a provision file from outside `fiware-idm`.
- Complete integration with Authzforce from the scratch:
  - Automatic domain creation and configuration in authzforce
  - Automatic POST from the uncoupled provision into Authzforce

I just wanted to point it out to reduce efforts, so feel free to check it, use it, or just discard it :)

Best!

**Comment by garcianavalon** [comment]
Hi!

Thank you very much for pointing this out, it will surely help us. I will take a look into it and give you some feedback too after creating our own Dockerfile and containers. ;)

Best regards!
Enrique

**Comment by albertinisg** [comment]
Glad to hear! :) If you have any doubts, comments or suggestions about it just let us know and we will try to help.

Best!
