### ISSUE TITLE
Documentation is wrong/incomplete

### ISSUE THREAD

**Issue by woutervddn** [ging/fiware-idm-deprecated#16]
fiware-idm `README.md` still refers to the following docker: `ging/idm` instead of `ging/fiware-idm`. Furthermore the requirements list:
- A

as a requirement.

**Comment by garcianavalon** [comment]
Fixed in edff440c875f0e1195de1fd27ff6757377f8210a and d795717f19867b165af446e0d743ebf1cf8bda4c.

Thanks.
