### ISSUE TITLE
Automatic installation guid

### ISSUE THREAD

**Issue by Miliks** [ging/fiware-idm-deprecated#17]
There is no text for automatic installation for the IdM for Installation and Administration guid.
Could you please provide the instruction for this?
Thanks in advance,

**Comment by garcianavalon** [comment]
Hi Miliks,
What version of the documentation are you seeing? There is definitely text in that section.
http://fiware-idm.readthedocs.org/en/latest/admin_guide.html#automated-installation-recommended
http://fiware-idm.readthedocs.org/en/latest/admin_guide.html#installing-the-back-end
http://fiware-idm.readthedocs.org/en/latest/admin_guide.html#installing-the-front-end

**Comment by Miliks** [comment]
Ok, the link u provided is valid, thanks.
But i was following the link from here https://github.com/ging/fiware-idm/tree/master/doc... and there there is no text, at least i can't see anything there.

**Comment by Miliks** [comment]
moreover the links provided in fiware catalog are not valid as well because they point to the following urls and not to the urls you just sent me in your message:
http://fiware-idm.readthedocs.org/en/latest/user_guide/
http://fiware-idm.readthedocs.org/en/latest/admin_guide/
...

**Comment by garcianavalon** [comment]
Thanks for reporting the issue. I will fix the links from the catalog.

About this link  https://github.com/ging/fiware-idm/tree/master/doc, where have you find it? The documentation should be read in http://fiware-idm.readthedocs.org and not in github. The reason is because the documentation has to be compiled from reStructuredText to html (or other formats) or you will see weird stuff like you had.

**Comment by Miliks** [comment]
Thanks for the quik reply.
I was looking for the guid on the catalog and since the links were broken i started to look for some info on the git, where u put the sources ... i know what very often there is a documentation also there.
Thanks again!

**Comment by garcianavalon** [comment]
Thank you for reporting the broken links ;)
I'll close the issue now.
