### ISSUE TITLE
Implicit Grant

### ISSUE THREAD

**Issue by GlockPL** [ging/fiware-idm-deprecated#2]
According to https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Identity_Management_-_KeyRock_-_User_and_Programmers_Guide impicit grant is supported but when I use "response_type=token" i still get access code.

**Comment by garcianavalon** [comment]
Hi,
I'll take a look at it.
Cheers.

**Comment by GlockPL** [comment]
Anything changed?

**Comment by garcianavalon** [comment]
Sorry, I had work to do in other areas. I've made some tests and looks like indeed it working incorrectly. I'll upload a fix tomorrow.
Cheers.

**Comment by garcianavalon** [comment]
Hi, this is already fixed it but not yet deployed in FIWARE Lab (if that applies to your case). It will be deployed along the following week.

I'll close the issue for now, I'll reopen it if problems appear after the deployment.
Cheers.

**Comment by helioft** [comment]
Hello,
We were wondering if this has been deployed?
Best

**Comment by garcianavalon** [comment]
Hi,
the update is scheduled for next Tuesday (July 7th).
BR
