### ISSUE TITLE
Error registering an application when logged as an Organization

### ISSUE THREAD

**Issue by aalonsog** [ging/fiware-idm-deprecated#20]
When you are logged as an organization and you try to register a new application, you get the error: 

Error: Unable to register the application.

**Comment by aalonsog** [comment]
Then... is the bug already fixed?

**Comment by federicofdez** [comment]
Hi,
It's been fixed in ging/horizon@b307e3f2931f3f5aba84d9c56984bbea75446919. 
Thanks for reporting the issue!
