### ISSUE TITLE
Can't get docker to work.

### ISSUE THREAD

**Issue by woutervddn** [ging/fiware-idm-deprecated#21]
I'm having a hard time configuring the docker image. When accessing the container we keep getting a "connection refused"-error. This error occurs even when using wget from the host device

I'm using this command to start the docker: 
`sudo docker run -d --name idm -v /home/ubuntu/host_config_file:/opt/idm/openstack_dashboard/local/local_settings.py -v /home/ubuntu/host_db_file:/opt/idm/keystone/keystone.db -p 80:8000 -p 5000:5000 -t  ging/fiware-idm`

with `/home/ubuntu/host_db_file`  being an empty file that has been created by using `touch` and `/home/ubuntu/host_db_file` baring these settings: http://pastebin.com/nC9tp46F

Any help would be greatly appreciated.

**Comment by garcianavalon** [comment]
Hi @woutervddn,

The docker image is experimental. Right now we are in process of discussing how should we use docker for the IdM. It makes little sense just to have a docker image, so we are probably going to implement a docker-compose file to do all the work required to make an IdM work.

I can't help you right now with your specific issue, sorry. The docker-compose (or whatever solution we decide to go for) should be implemented by next week.

Best regards
