### ISSUE TITLE
No keystone commands can be run

### ISSUE THREAD

**Issue by antonis179** [ging/fiware-idm-deprecated#23]
The installation completed successfully from "http://fiware-idm.readthedocs.org/en/latest/admin_guide.html" and all the endpoints are functioning correctly.

However while trying to setup keyrock to function with the Object Storage GE by following this guide "http://thornelabs.net/2014/07/16/authenticate-openstack-swift-against-keystone-instead-of-tempauth.html" any command that involves "keystone" returns " 'module' object has no attribute '**version**' "

**Comment by garcianavalon** [comment]
I'll take a look into it.
For now, you can make the same steps using curl (or any other tool of your choice) using the API directly
http://developer.openstack.org/api-ref-identity-v3.html

**Comment by garcianavalon** [comment]
that keystone command is not referring to the IdM installed keystone, as we don't install that command. It might be installed in the machine from another source. Use the API instead

**Comment by garcianavalon** [comment]
I'll close this issue for now as is not related to the IdM. Feel free to open it again.
