### ISSUE TITLE
Assign/Remove Role from user return 404 error

### ISSUE THREAD

**Issue by Jaredmmx** [ging/fiware-idm-deprecated#24]
I 'm creatibg a PHP class to provide access to fiware-idm services

Everything works fine except for user role assignment and removal

CREATE USER:
2015/10/28 11:39:07 [keyrock] [application] Keyrock Create User: Array
(
    [userName] => jesus
    [displayName] => Jesus Apellido
    [id] => jesus
    [urn:scim:schemas:extension:keystone:2.0] => Array
        (
            [domain_id] => default
        )

```
[active] => 1
[emails] => Array
    (
        [0] => Array
            (
                [value] => username@gmail.com
            )

    )

[schemas] => Array
    (
        [0] => urn:scim:schemas:core:2.0
        [1] => urn:scim:schemas:extension:keystone:2.0
    )
```

)

GET USER DETAILS:
2015/10/28 11:39:07 [keyrock] [application] Keyrock Get User: Array
(
    [userName] => jesus
    [displayName] => Jesus Apellido
    [id] => jesus
    [urn:scim:schemas:extension:keystone:2.0] => Array
        (
            [domain_id] => default
        )

```
[active] => 1
[emails] => Array
    (
        [0] => Array
            (
                [value] => username@gmail.com
            )

    )

[schemas] => Array
    (
        [0] => urn:scim:schemas:core:2.0
        [1] => urn:scim:schemas:extension:keystone:2.0
    )
```

)

LIST USERS (using Keystone v3 API): mind the lack of 'username' in the new created user
2015/10/28 11:39:07 [keyrock] [application] Keyrock List Keystone Users: Array
(
    [users] => Array
        (
            [0] => Array
                (
                    [username] => idm
                    [name] => idm
                    [links] => Array
                        (
                            [self] => http://192.168.10.36:5000/v3/users/idm
                        )

```
                [domain_id] => default
                [enabled] => 1
                [id] => idm
                [default_project_id] => 89d7d83110b4428d80c5934e5a34323f
            )

        [1] => Array
            (
                [username] => 
                [description] => Jesus Apellido
                [links] => Array
                    (
                        [self] => http://192.168.10.36:5000/v3/users/jesus
                    )

                [enabled] => 1
                [email] => username@gmail.com
                [id] => jesus
                [domain_id] => default
                [name] => jesus
            )

    )

[links] => Array
    (
        [self] => http://192.168.10.36:5000/v3/users
        [previous] => 
        [next] => 
    )
```

)

ASSIGN USER ROLE:

KeyrockHelper::assignUserRole( jesus , 2f3086d19b914c5792767d5ddeab37a8 , a251df3b17ac4dd499fdf1780910d43e )
->
ERROR: HTTP error 404 occurred when trying to fetch REQUEST
(
 http://192.168.10.36:5000/v3/OS-ROLES/users/jesus/applications/2f3086d19b914c5792767d5ddeab37a8/roles/a251df3b17ac4dd499fdf1780910d43e
)

Any idea why that 404 error is issued?

**Comment by garcianavalon** [comment]
Hi @Jaredmmx ,

I'm not very familiar with PHP syntax, so I'm not sure exactly how are you authenticating. Which token are you using to authenticate the assignUserRole call? It should be one of a user that is either admin in Keystone or has the provider role assigned in the 2f3086d19b914c5792767d5ddeab37a8 application.

**Comment by Jaredmmx** [comment]
There's no PHP code in this.... just JSON response bodies and/or headers.

I'm sending the following HEADERS:
 HEADERS: Array
(
    [User-Agent] => Array
        (
            [0] => GuzzleHttp/6.1.0 curl/7.36.0 PHP/5.5.12
        )

```
[Host] => Array
    (
        [0] => 192.168.10.36:5000
    )

[Content-Type] => Array
    (
        [0] => application/json
    )

[X-Auth-Token] => Array
    (
        [0] => ADMIN
    )
```

)

where 'ADMIN' corresponds to the admin_token configured in keystone.conf file

Anyway.... I guess if that was the reason I should get an Autehtication Error or  a Forbidden error (500....), not a 404.

ASSIGN USER ROLE call is made through a PUT request as documentation says...

**Comment by garcianavalon** [comment]
woops, my mistake. I read 403.
If you are getting a 404 one of the resources doesn't exists. Do a get for one of each and find out which one is missing:
GET /v3/users/user_id
GET /v3/OS-ROLES/consumers/consumer_id (application is called consumer in OAuth)
GET /v3/OS-ROLES/roles/role_id
More documentation about this here http://docs.keyrock.apiary.io/#reference/keystone-extensions/rol/read-role-details
and here http://developer.openstack.org/api-ref-identity-v3.html

PD: I don't understand your JSON then :smile: It looks like a logger or console output of the response headers and body, a little confusing to read ;)

**Comment by garcianavalon** [comment]
I understand this is issue is resolved. 
@Jaredmmx  feel free to open it again if not.
