### ISSUE TITLE
[bug] fabfile deployments scripts of keystone and horizon are not compatible with docker cache

### ISSUE THREAD

**Issue by ghost** [ging/fiware-idm-deprecated#29]
According to [this documentation source](https://docs.docker.com/engine/articles/dockerfile_best-practices/#apt-get) docker cache only check latest version of 

```
RUN sudo apt-get update && \
    sudo apt-get install -y wget python python-dev git && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py
```

src https://github.com/ging/fiware-idm/blob/master/extras/docker/Dockerfile

The **problem** is that if they are in the latest version, **no** apt-get update is performed, but could be required for dependencies of deployment of keystone and horizon in line `lrun('sudo apt-get install -y {0}'.format(dependencies))` of these fabfiles:
- https://github.com/ging/fiware-idm/blob/master/deployment/keystone.py
- https://github.com/ging/fiware-idm/blob/master/deployment/horizon.py

short solution is to put `lrun('sudo apt-get update` for each fabfile, this means 3 times apt-get update will be executed, but is the correct way. I don't know better approach.

**Comment by ghost** [comment]
So perhaps that's why bitergia's dockerfile include all that dependencies at the beginning
https://github.com/Bitergia/fiware-chanchan-docker/blob/master/images/idm-keyrock/4.3.0/Dockerfile
(I don't know if there are all)

**Comment by garcianavalon** [comment]
same answer as https://github.com/ging/fiware-idm/issues/32
