### ISSUE TITLE
[documentation] Fix inconsistencies of Keyrock API

### ISSUE THREAD

**Issue by ghost** [ging/fiware-idm-deprecated#31]
After long hard work I could start working with Keyrock API, because I didn't know where was the problem.

Please, fix inconsistencies in Keyrock API:
http://docs.keyrock.apiary.io/

If I can help contributing, tell me.

Example with http://docs.keyrock.apiary.io/#reference/keystone-extensions/consumers/list-consumers `GET http://keyrock/OS-OAUTH2/consumers` is not very self explanatory. Reading about general OAuth2 does not help.

To get it working in the fastest way:
`curl -H "X-Auth-Token: ADMIN" http://keyrock:5000/v3/OS-OAUTH2/consumers`

Where keyrock is domain name or ip address. Assuming that you are using keystone on default port 5000. Alternatively you can get a X-Auth-Token with Keystone API.

**Comment by federicofdez** [comment]
Hi!

Thanks for writing. The need of an Auth Token header when making requests to the Keystone API (and therefore the Keyrock API) is shown [here](http://docs.openstack.org/developer/keystone/api_curl_examples.html). We agree that this might not be quite emphasized in the Keyrock API explanation, so we'll change it within the next few days to make it more self explanatory.

After taking a deep look at the API, we couldn't find any more inconsistencies, so we encourage you to tell us about about any other one you might find. Only this way will we be able to improve our docs.

Thank you,

**Comment by garcianavalon** [comment]
Seems solved. I'll close this for inactivity, feel free to open it again.
