### ISSUE TITLE
oslo.i18n dependency error while trying to install keystone

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-idm-deprecated#37]
When trying to install keystone, both by following the automated install and the manual install of the documentation, it fails with the following error:

```
error: oslo.i18n 1.3.1 is installed but oslo.i18n<1.6.0,>=1.5.0 is required by set(['oslo.utils'])
```

Trying to install a higher version of oslo.i18n seems to break another dependecies.
The error happens with both the keyrock-4.4.1 release tag and the latest version.

**Comment by garcianavalon** [comment]
This should be fixed in the new release. Reopen this issue if you still encounter an error.
https://github.com/ging/keystone/commit/633cc96d76b3c8cc1e302086ebcd4045bc3e668b
