### ISSUE TITLE
Changing horizon ports

### ISSUE THREAD

**Issue by DerJayDee** [ging/fiware-idm-deprecated#38]
Well well, me again, sorry to bother but I ran into another problem: I tried to serve the horizon dashboard via SSL. That worked pretty well by simply redirecting the previous used url to my apache ssl port behind what i dropped the whole django part. The only problem with this is, that the logout action wants to request a normal http-ressource via XmlHTTPRequest and therefore it uses the ssl port but with a http protocol.

So is there an option to define custom ports or change the logout url (/auth/logout) to use https aswell?

**Comment by garcianavalon** [comment]
Hi @DerJayDee , no problem ;)

To logout the IdM uses a js call to implement a single sign out in all of the specified websites. You can see the file [here](https://github.com/ging/horizon/blob/master/openstack_dashboard/static/fiware/signOut.js). By default it will use `developmentCall`. Edit your file [changing this line](https://github.com/ging/horizon/blob/master/openstack_dashboard/static/fiware/signOut.js#L100) to https. That should be enough.

Cheers!

**Comment by DerJayDee** [comment]
Thank you, works like a charm!
