### ISSUE TITLE
Send XACML policy to Authzforce through console

### ISSUE THREAD

**Issue by albertinisg** [ging/fiware-idm-deprecated#4]
Hi!

We are using IdM, PEP and Authzforce for the [FIWARE Devguide APP](https://github.com/Bitergia/fiware-devguide-app). What we are doing is to provide a set of users, organizations, applications, roles and permissions by default (to be used with Docker).

Right now we did good until here, but now we are a bit stuck at some point. We have the whole environment running but, the only thing that we still were not able to do is to send XACML policy to Authzforce from the beginning.

By default Authzforce permits all, but we would like to parse all the generated roles and permissions in our application without having to navigate through Horizon interface. Is there any way to trigger that? (we would like to avoid the step of going to IdM - Application - Manage Roles - Save)

We've tried ourselves re-writing the function `handle` from `/horizon/openstack_dashboard/dashboards/idm/myApplications/workflows.py`, but in the end we've messed with the environments and paths so we couldn't apply it in an easy way.

Any help would be appreciated! :)

**Comment by aalonsog** [comment]
Hi, you have to use the AuthZForce API directly. Here you will find the documentation: 
http://catalogue.fiware.org/enablers/authorization-pdp-authzforce
If you have doubts regarding the use of it please contact the GE owner (contact info included also there)

BR
