### ISSUE TITLE
Link to chef cookbook broken

### ISSUE THREAD

**Issue by hansjd** [ging/fiware-idm-deprecated#41]
https://github.com/ging/fiware-idm/tree/master/extras/chef/fiware-idm

guessing this is the correct link: https://github.com/ging/fiware-idm/tree/master/extras/chef

**Comment by garcianavalon** [comment]
thanks for your feedback! I'll fix it

**Comment by garcianavalon** [comment]
Fixed in https://github.com/ging/fiware-idm/commit/8c5ff43838e52c7cc6840406deb881b2560a2a1d
