### ISSUE TITLE
where is documentation for running keystone as service?

### ISSUE THREAD

**Issue by hansjd** [ging/fiware-idm-deprecated#42]
at the end of installing backend, it says...

```
Finally, if you want to run the keystone backend in the backgroud you can :ref:`install it as a service <keystone-as-service>`.
```

is this part missing in the docs, or is it suppose to link somewhere else?

**Comment by DerJayDee** [comment]
Preface: I am no dev of keystone and every step I describe below you will follow at your own risk.

Create a file daemon.sh inside your keystone directory (in my case /opt/keystone, you might need to change that) containing the following:

```
#! /bin/bash

cd /opt/keystone
source .venv/bin/activate
./bin/keystone-all -v 1>> /var/log/keystone/out.log 2>> /var/log/keystone/err.log
```

and a file keystone in /etc/init.d containintg the following:

```
#!/bin/sh

### BEGIN INIT INFO
# Provides:          keystone
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the keystone service
# Description:       Starts the keystone service inside its venv so that the public port will be available as port 5000 and the admin port as port 37375
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/opt/keystone
DAEMON=$DIR/daemon.sh
DAEMON_NAME=keystone

# Add any command line options for your daemon here
DAEMON_OPTS=""

# This next line determines what user the script runs as.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    pkill -P `cat $PIDFILE`
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
```

After reloading your init.d configs you should be able to use it as a normal service.

**Comment by federicofdez** [comment]
Hi @hansjd,

There seems to be a broken link in the `README.rst` file. Thanks for reporting it!

The link should point to the [project's official docs](http://fiware-idm.readthedocs.org/en/latest/admin_guide.html#configuring-keystone-as-a-service), where we provide a basic example to let you configure Keystone as a service, in some way similar to what @DerJayDee just told you.

Hope this helps,

Cheers!

> Remember that the `README.rst` file is just an entry point. The full documentation can be found [here](http://fiware-idm.readthedocs.org/en/latest/index.html).

**Comment by garcianavalon** [comment]
Closing this issue. Feel free to open it again if the issue persits.

**Comment by garcianavalon** [comment]
For reference, I added a link to the relevant README section that renders correctly in GitHub to the ReadTheDocs documentation in https://github.com/ging/fiware-idm/commit/71591998170a8e821649066e69267629e013a1bd
