### ISSUE TITLE
check_activated_two_factor() got an unexpected keyword argument 'user_name'

### ISSUE THREAD

**Issue by mkard** [ging/fiware-idm-deprecated#44]
Hi All,

I have installed  the new  release (5.1.0) ( horizon and keystone) but when I try to login with idm user I receive the error: 
check_activated_two_factor() got an unexpected keyword argument 'user_name'
while I try to signup a new user I receive the error: Reverse for 'signup' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Please is there any explanation on that symptom?

**Comment by federicofdez** [comment]
Hi @mkard,

Thanks for reporting this issue. We are working on several improvements in the authentication module, which Horizon uses as dependency, and this must have made the stable version fail. Sorry for the inconveniences this might have caused you.

Anyway, I just updated the dependency (ging/django_openstack_auth@1289daadf52cf5278cb36fcbf21dd29f25d38ce1) to make it work again. To fix your installation, you just need to reinstall the dependencies again, running the following from your Horizon directory:

```
sudo python tools/install_venv.py
```

Please, let me know if there is still anything not working properly.

Cheers!

**Comment by mkard** [comment]
Hi Federico,

I would like to thank you for your immediate reaction. Everything are ok
now.

Best Regards
Marinos

2016-02-18 13:49 GMT+02:00 Federico Fernández notifications@github.com:

> Hi @mkard https://github.com/mkard,
> 
> Thanks for reporting this issue. We are working on several improvements in
> the authentication module, which Horizon uses as dependency, and this must
> have made the stable version fail. Sorry for the inconveniences this might
> have caused you.
> 
> Anyway, I just updated the dependency (ging/django_openstack_auth@1289daa
> https://github.com/ging/django_openstack_auth/commit/1289daadf52cf5278cb36fcbf21dd29f25d38ce1)
> to make it work again. To fix your installation, you just need to reinstall
> the dependencies again, running the following from your Horizon directory:
> 
> sudo python tools/install_venv.py
> 
> Please, let me know if there is still anything not working properly.
> 
> Cheers!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ging/fiware-idm/issues/44#issuecomment-185679925.

## 

Kardaris Marinos
Systems Engineer - Aviation Expert

_Future Intelligence Ltd._
Technological & Scientific Park of Attica "Lefkippos"
NCSR Demokritos
Branch: Scientific & Technological Park of Epirus
University of Ioannina
P: (+30) 2130417996 M: (+30)
F: (+30) 2130021245
mkardariss@f-in.gr kanastasopoulos@f-in.gr
http://f-in.gr
