### ISSUE TITLE
NoReverseMatch at /sign_up/

### ISSUE THREAD

**Issue by mkard** [ging/fiware-idm-deprecated#45]
In the last version, while the first problem (login as idm user ) is solved I can't signup a new user.
I receive the following error:

NoReverseMatch at /sign_up/
Reverse for 'signup' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method: POST
Request URL:    http://192.168.200.189:8000/sign_up/
Django Version: 1.6.11
Exception Type: NoReverseMatch
Exception Value:  
Reverse for 'signup' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location: /home/fint/horizon/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 456
Python Executable:  /home/fint/horizon/.venv/bin/python
Python Version: 2.7.6
Python Path:  
['/home/fint/horizon',
 '/home/fint/horizon/.venv/src/openstack-auth',
 '/home/fint/horizon/.venv/src/python-keystoneclient',
 '/home/fint/horizon/.venv/lib/python2.7',
 '/home/fint/horizon/.venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/fint/horizon/.venv/lib/python2.7/lib-tk',
 '/home/fint/horizon/.venv/lib/python2.7/lib-old',
 '/home/fint/horizon/.venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/fint/horizon/.venv/local/lib/python2.7/site-packages',
 '/home/fint/horizon/openstack_dashboard']

**Comment by federicofdez** [comment]
Hi @mkard,

Thanks for writing. Could you please give me more detail about the version of Keystone and Horizon that you're currently running? I understand that you're running the latest release (v5.1.0) of both components, but wanted to be sure anyway in order to recreate your situation.

**Comment by mkard** [comment]
Ηι,

Yes , the release is v5.1.0

2016-02-23 10:32 GMT+02:00 Federico Fernández notifications@github.com:

**Comment by federicofdez** [comment]
Hi,

As you may have seen, after looking into your problem, I finally found out where exactly the reverse issue was, and fixed it in https://github.com/ging/horizon/commit/10851f96e64d77ed5292e0cb5ce8bfc0d8200876. You can either cherry-pick this commit or wait for the new release (v5.1.1) to come out, which will happen within the next few days. Thanks for your report!

However, note that that line of code is only reached if something goes wrong when registering the user (I myself managed to register a couple users before coming back to you). My guess is that the _I want to be a trial user_ box was checked when you were trying to register the user and, since this checkbox is actually intended for the FIWARE Lab Keyrock instance, the registration process would fail.

**My recommendation is that you don't need to check this box in order to register users in your own Keyrock instance.** Anyway, it shouldn't break either now that I fixed it.

Hope this helps!!

Cheers

**Comment by mkard** [comment]
Hi,

Thank you for your answer. I did the modification and now I can create a
new user and I receive the message that the user is created.
Also I can check it as idm user
But when I try to login , I receive the message Invalid user name or
password
I have left the default settings for e-mail. I don't known if this create
the problem because in the log file of keystone I read " that the "_user is
disabled:mkard_"
When I tried to set the Email parameters I receive the error: EMAIL_HOST
 Indentation Error  in horizon console

thank's a lot
Marinos

2016-02-24 13:02 GMT+02:00 Federico Fernández notifications@github.com:

**Comment by federicofdez** [comment]
Hi,

After registration, the user receives an email with an activation link, and their account won't activate until this link is accessed.

In a production environment, Keyrock would actually send the email, but in a development environment we use Django console email backend, which outputs the email to the Horizon console. Therefore, all you need to do to activate the account you just registered is head towards the console and look for a link like this one in the email content:

```
http://localhost:8000/activate/?activation_key=f95bd139c84c4d6fac99e82f96cf6a99&amp;user=user_name
```

where `user_name` will be the one you chose in the registration process. **Just follow this link from your browser and the account will be activated**.

> **Note:** by default, the activation URL begins with `https://account.lab.fiware.org`. You can either copy-paste just from `/activate` onwards or update the `EMAIL_URL` setting in the `local_settings.py` file. You can leave the rest of the email parameters as default.

Let me know if this works!

**Comment by mkard** [comment]
Hi,

Yes , this procedure via console it works.For the development phase it is OK

For once more time
Thank's a lot
Have a nice weekend

Marinos

2016-02-26 10:50 GMT+02:00 Federico Fernández notifications@github.com:
