### ISSUE TITLE
Fabre Apiary Rendering of JSON examples is not correctly indented

### ISSUE THREAD

**Issue by jmcanterafonseca** [ging/fiware-idm-deprecated#47]
for instance at

Create a Consumer  POST /OS-OAUTH2/consumers

**Comment by federicofdez** [comment]
Hi @jmcanterafonseca,

I just checked http://docs.keyrock.apiary.io/ and everything seems to be rendering correctly there. Anyway, let me check this with Fabre. I'll come back to you ASAP.

Thanks!

**Comment by jmcanterafonseca** [comment]
I'm referring to

http://ging.github.io/fiware-idm/keyrock.html

2016-03-01 19:40 GMT+01:00 Federico Fernández notifications@github.com:

**Comment by aalonsog** [comment]
Hi José Manuel, 

we usually edit .apib file in Apiary website and then send it to you in order to generate the HTML/PDF with Fabre. Do you know how we can update the document to fix those indentations?

Thanks in advance

**Comment by aalonsog** [comment]
Ok... I guess editing the indentations there should work. We are going to fix them.

**Comment by jmcanterafonseca** [comment]
Hi Alvaro,

Now Fabre is ready to be used as any other FIWARE tool, please check
github.com/fiware/tools.Fabre

thanks

2016-03-02 10:43 GMT+01:00 Álvaro Alonso notifications@github.com:

**Comment by federicofdez** [comment]
Fixed in https://github.com/ging/fiware-idm/commit/b98ec48f1073cd3e184753721a066073ab036265. If there's anything still not showing properly, just let us know.

Thanks!
