### ISSUE TITLE
How to use the API¿?

### ISSUE THREAD

**Issue by xabies** [ging/fiware-idm-deprecated#5]
Hi I'm a newbie developer. I have follow the isntallation guide without problems, but now I do not know waht to do?

I have the http://localhost:8000/ runnig the fiware Lab form and I can with the idp user.

Now I want to use the rest ful api to create user or list user of my app:
GET /v2/Users/
but I don not how to do that? I only obtain errors. What is the next step.

**Comment by j99ht** [comment]
Hi xabies.

It is only working v3

**Comment by garcianavalon** [comment]
Hi @xabies ,

as @j99ht pointed out, we recommend the use of the v3 API, as the v2 is deprecated by the OpenStack team. On how to use the API, you can find some information in the Keystone documentation:
http://docs.openstack.org/developer/keystone/api_curl_examples.html
http://developer.openstack.org/api-ref-identity-v3.html

If you can't find what you are looking for, please explain me your use case and what do you intend to do so I can help you better. I'll close the issue for now, reopen it if needed.

Cheers.
