### ISSUE TITLE
Keyrock vs OpenStack

### ISSUE THREAD

**Issue by drasko** [ging/fiware-idm-deprecated#50]
Hello,
I am trying to understand what are really the changes done on Keystone and Horizon forks by GING and are these needed only for the Fiware Lab (i.e. are the Fiware Lab specific)?

We are making our proper Fiware installation for Mainflux IoT Cloud: https://github.com/Mainflux/mainflux, and we are using Orion and IoT Agents. We want to add security layer with Wilma and IDM, and we are wondering if we need Keyrock modifications, or we can use vanilla Keystone and Horizon from OpenStack directly.

Will Wilma work with unchanged Keystone and Horizon from OpenStack?

BR,
Drasko

**Comment by aalonsog** [comment]
Hi, I've just answered your question in the SOF thread. BR

**Comment by drasko** [comment]
Thanks,
but please update the answers here: http://stackoverflow.com/questions/35952672/keyrock-vs-openstack

BR,
Drasko
