### ISSUE TITLE
Provide versioned tags for the docker images.

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-idm-deprecated#51]
The [FIWARE Docker guidelines](http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Docker) says:

>  At least a Docker container tag associated with the latest stable release MUST be present in Dockerhub.

The automated image only has the `latest` tag.

Please add versioned tags to the docker image, at least for the latest stable release.

**Comment by aalonsog** [comment]
Done: 
https://hub.docker.com/r/fiware/idm/tags/
