### ISSUE TITLE
API Key support for Keyrock

### ISSUE THREAD

**Issue by gasampong** [ging/fiware-idm-deprecated#52]
Currently the flow of Keyrock is as follows:

=>You go to your protected resource
=>You are redirected to login via fiware labs login form
=>Once you have been successfully authenticated you are redirected back to the authenticated resource

What I would like is a way to link an account on fiware labs to an API Key so that you can use that as opposed to having to login with a username and password.

**Comment by federicofdez** [comment]
Hi @gasampong ,

I'm afraid I didn't actually get to understand your situation. Keyrock complies with the OAuth2 standard described in [RFC 6749](http://tools.ietf.org/html/rfc6749) and supports all four grant types defined there:
- Authorization Code Grant
- Implicit Grant
- Resource Owner Password Credentials Grant
- Client Credentials Grant

You may use the one that best fits your app purposes. Just have a look at [the docs](http://fiware-idm.readthedocs.org/en/v5.2.0/oauth2.html) and come back to us if you still don't find an answer.

Best regards,

**Comment by federicofdez** [comment]
Seems to be solved.

Thanks for writing!
