### ISSUE TITLE
Output from Phase3

### ISSUE THREAD

**Issue by IAIS4EP** [ging/fiware-idm-deprecated#54]
Dear Keyrock team,

at our Accelerator EUROPEANPIONEERS, we have tested some Enablers, also KeyRock.

One of our results is a Docker-based UI showcase for this component.
Do you think this could be a useful contribution to the project, allowing new developers very easy visual access to Enabler features, with 1 minute setup?
Please have a look:
https://github.com/IAIS4EP/fiware/tree/master/ge/ge_keyrock/Web%20Client%20Testing%20App

We can setup a call to answer your questions if you like.

kind regards
Peter

**Comment by federicofdez** [comment]
Hi @IAIS4EP ,

Thanks for writing and telling us about your showcase. We will definitely take a deep look into it.

Best regards,

Federico Fernández

**Comment by IAIS4EP** [comment]
@FedericoFdez  when can we have your feedback?

**Comment by federicofdez** [comment]
Hi @IAIS4EP ,

Thank you for your contribution. I'll close the issue now.

Kind regards,
Federico Fernández

**Comment by IAIS4EP** [comment]
Dear Federico, I would like to have feedback on our contribution if possible! Can we make it to an acceptable pull request?
kind regards
Peter

**Comment by federicofdez** [comment]
Hi again @IAIS4EP ,

We did check your showcase, and found it rather interesting. Unfortunately, I'm afraid we currently don't merge this kind of contributions. We hope you still want to keep it in your repo, in case anyone in the community finds it useful. So thanks again for your contribution!

Regards,
Federico Fernández
