### ISSUE TITLE
Issue when checking  oauth2 token (client_credentials grant)

### ISSUE THREAD

**Issue by aalonsog** [ging/fiware-idm-deprecated#55]
When sending a validation request (/v3/access-tokens/{token}) with an Oauth2 token created using grant_type=client_credentials, the response is

{
  "error": {
    "message": "object of type 'NoneType' has no len()",
    "code": 400,
    "title": "Bad Request"
  }
}

**Comment by federicofdez** [comment]
Solved in https://github.com/ging/keystone/commit/faa2a88d0db9c0f0b5d16af836b3ec37d568c61c but still to be deployed.
