### ISSUE TITLE
Run with nginx

### ISSUE THREAD

**Issue by superp** [ging/fiware-idm-deprecated#57]
Hi, all.
I have a few questions by Keyrock installation. 
I installed keyrock and horizon to my server, but how can I configure my own domain to this service?
And how I can do it with nginx?

**Comment by federicofdez** [comment]
Hi @superp ,

Regarding configuration of your own domain, and therefore the deployment of KeyRock, we provide some guidelines to do it with **Apache and mod_wsgi** in [our docs](http://fiware-idm.readthedocs.org/en/v5.2.0/setup.html#web-server-apache-mod-wsgi).

Anyway, Horizon is no different from any other Django web project, and therefore its primary deployment platform is WSGI, the Python standard for web servers and applications. What this means is that any module which can host a Python WSGI application should work with Horizon as well. I'm not an expert in nginx, but I've seen it can work with **uWSGI** as a reverse proxy, so I don't think it will be a hard task for you to set it up.

As for Keystone, we recommend to run it as a service if it's running in a deployment environment. Check [this link](http://fiware-idm.readthedocs.org/en/v5.2.0/admin_guide.html#configuring-keystone-as-a-service) in our docs to find out how to do so.

Hope this helps!

**Comment by federicofdez** [comment]
I'll close the issue now, but feel free to reopen it if we can be of further help.

Cheers!

**Comment by superp** [comment]
@federicofdez Thanks you!
I decided to install it by apache and have new problems, here more info https://github.com/ging/fiware-idm/issues/63

**Comment by federicofdez** [comment]
@superp I answer you in #63 then!
