### ISSUE TITLE
Authzforce application domain not returned with user_info.

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-idm-deprecated#58]
When the pep proxy request the user_info to keystone, the application domain in authzforce is not returned, even though it exists.  The problem is this lines on [controllers.py](https://github.com/ging/keystone/blob/master/keystone/contrib/roles/controllers.py#L448):

``` python
if getattr(application, 'ac_domain', None):
    response_body['app_azf_domain'] = application.ac_domain
```

Here, `application` is a dictionary, not an object, so getattr always fails to find `ac_domain`.  Something like this should work:

``` python
if 'ac_domain' in application:
    response_body['app_azf_domain'] = application['ac_domain']
```

**Comment by federicofdez** [comment]
Hi @dmabtrg 

Thank you for writing. You are right: the `ac_domain` wasn't being properly retrieved. We just fixed it in ging/keystone@009e96d8fe32571f3ffa34677cbf6054451d7aa1. It should all work now.

Regards,
Federico Fernández
