### ISSUE TITLE
Tag DockerHub releases of official Fiware repo

### ISSUE THREAD

**Issue by drasko** [ging/fiware-idm-deprecated#59]
Only 5.1 is tagged: https://hub.docker.com/r/fiware/idm/tags/

What about others? What does `latest` tag correspond here? 5.2?

Please tag with release version.

**Comment by federicofdez** [comment]
Hi all,

Release 5.2.0 is now available in DockerHub. The `latest` tag corresponds to the latest commit at GitHub, not to the latest release.

I'll close the issue now

Best regards,
Federico Fernández
