### ISSUE TITLE
Do not use hard-coded password

### ISSUE THREAD

**Issue by drasko** [ging/fiware-idm-deprecated#61]
Here: https://github.com/ging/fiware-idm/blob/master/extras/docker/expect_idm_password#L4, keystone password is hard-coded.

Please use either ENV variable, or one from some other config file, as this can be passed into contained in the moment of deployment via `docker-compose.yml`

**Comment by drasko** [comment]
Similarely here: https://github.com/ging/fiware-idm/blob/master/extras/docker/Dockerfile#L28 - please do NOT replace `$$IDM_PASS` from `horizon/openstack_dashboard/local/local_settings.py` with hard-coded pass.

File `horizon/openstack_dashboard/local/local_settings.py` can be mapped into the docker from host PC via `volumes` directive.

If you really need to replace - use ENV variables or some idm config files that we can map into container from host PC.

We need to be capable to customize Docker deployments!

**Comment by federicofdez** [comment]
Hi @drasko ,

I understand your situation, and just made a few improvements to support more cases like yours. You can now find (https://github.com/ging/fiware-idm/commit/e22d0036a686dc34934c9663b71c84e483973cb7) an environment variable called `IDM_PASS` declared with the `ENV` docker statement.

I hope this solves your issue, but feel free to come back to us in any other case.

Best regards,
Federico Fernández
