### ISSUE TITLE
Add support for Authzforce 4.4.x

### ISSUE THREAD

**Issue by dmabtrg** [ging/fiware-idm-deprecated#62]
The current release of Authzforce and the one available on the [catalogue](http://catalogue.fiware.org/enablers/authorization-pdp-authzforce) is version 4.4.1, but both idm and pep-wilma only work with version 4.2.0, as there are some changes in the urls and xml.  Please consider adding support for the new Authzforce version.  The main changes seems to be:
- The default url begins with `/authzforce-ce` instead of `/authzforce`.  Right now this path is hardcoded in horizon (lines [47](https://github.com/ging/horizon/blob/master/openstack_dashboard/fiware_api/access_control_ge.py#L47) and [103](https://github.com/ging/horizon/blob/master/openstack_dashboard/fiware_api/access_control_ge.py#L103)).
- The xml to create a new domain has changed.  Instead of

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<taz:properties xmlns:taz="http://thalesgroup.com/authz/model/3.0/resource">
    <name>MyDomain</name>
    <description>This is my domain.</description>
</taz:properties>
```

the new xml is:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:domainProperties xmlns:ns4="http://authzforce.github.io/rest-api-model/xmlns/authz/4" externalId="external0">
    <description>This is my domain</description>
</ns4:domainProperties>
```
- The request to create a new domain has to be a `POST` instead of `PUT`.
- The url to add policies has changed to `/authzforce-ce/domains/<domain_id>/pap/policies` (changes `policySet` to `policies`).  The xml to create new policies doesn't seem to have changed.

Thanks.

**Comment by aalonsog** [comment]
Thanks! We have added this as a new feature for the GE. In will be available in the next release.

BR
