### ISSUE TITLE
Get error when running horizon

### ISSUE THREAD

**Issue by superp** [ging/fiware-idm-deprecated#63]
Sorry for a new issue, but I need help with running horizon at apache & wsgi.
This is my log:

`File "/var/www/horizon/.venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
   File "/var/www/horizon/.venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
     self._urlconf_module = import_module(self.urlconf_name)
   File "/var/www/horizon/.venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
     __import__(name)
   File "/var/www/horizon/openstack_dashboard/wsgi/../../openstack_dashboard/urls.py", line 36, in <module>
     from openstack_dashboard.dashboards.idm_admin.user_accounts \\
   File "/var/www/horizon/openstack_dashboard/wsgi/../../openstack_dashboard/dashboards/idm_admin/user_accounts/views.py", line 28, in <module>
     from openstack_dashboard.dashboards.idm_admin.user_accounts \\
   File "/var/www/horizon/openstack_dashboard/wsgi/../../openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 195, in <module>
     class UpdateAccountForm(forms.SelfHandlingForm, UserAccountsLogicMixin):
   File "/var/www/horizon/openstack_dashboard/wsgi/../../openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 202, in UpdateAccountForm
     choices=get_account_choices())
   File "/var/www/horizon/openstack_dashboard/wsgi/../../openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 172, in get_account_choices
     use_idm_account=True),
   File "/var/www/horizon/openstack_dashboard/wsgi/../../openstack_dashboard/fiware_api/keystone.py", line 818, in get_basic_role
     request, basic, lambda req, n: internal_keystoneclient(req).roles.find(name=n))
   File "/var/www/horizon/openstack_dashboard/wsgi/../../openstack_dashboard/fiware_api/keystone.py", line 797, in _get_element_and_cache
     exceptions.handle(request)
   File "/var/www/horizon/openstack_dashboard/wsgi/../../horizon/exceptions.py", line 324, in handle
     messages.error(request, message or log_entry)
   File "/var/www/horizon/openstack_dashboard/wsgi/../../horizon/messages.py", line 83, in error
     fail_silently=fail_silently)
   File "/var/www/horizon/openstack_dashboard/wsgi/../../horizon/messages.py", line 41, in add_message
     if not horizon_message_already_queued(request, message):
   File "/var/www/horizon/openstack_dashboard/wsgi/../../horizon/messages.py", line 28, in horizon_message_already_queued
     if request.is_ajax():
 AttributeError: 'NoneType' object has no attribute 'is_ajax'`

**Comment by federicofdez** [comment]
Hi @superp ,

The `'NoneType' object has no attribute 'is_ajax'` error usually appears when Horizon can't successfully connect to Keystone. Did you set the right `OPENSTACK_HOST` and `OPENSTACK_KEYSTONE_URL` in your `local_settings.py` file?

**Comment by superp** [comment]
@federicofdez yes, I set localhost:

```
OPENSTACK_HOST = "127.0.0.1"
OPENSTACK_KEYSTONE_URL = "http://%s:5000/v3" % OPENSTACK_HOST
# NOTE(garcianavalon) this role is created whith all the other initial
# data. Don't confuse it with keystone v2 API default role
# (member_role_name=_member_)
OPENSTACK_KEYSTONE_DEFAULT_ROLE = "member"

# Disable SSL certificate checks (useful for self-signed certificates):
OPENSTACK_SSL_NO_VERIFY = True
```

How can i check test connection for keystone in terminal?

**Comment by superp** [comment]
@federicofdez I run keystone in development mode and it works!
It's mean that `sudo service keystone_idm start` not run keystone as service.

**Comment by federicofdez** [comment]
Hi @superp ,

I'm glad to see that it's now working! Anyway, Keystone should be set as a service when running in a deployment environment, so feel free to write back if you're having trouble when doing so.

Cheers!

**Comment by superp** [comment]
and finally, I run it as service (just changed /etc/init/keystone_idm.conf line cd $absolute_keystone_path to my origin keystone path).
But, I have a new trouble ))
I can't create any application, roles and can't Sing up new users in my profile (logined as idm user).
Here is my project http://keyrock.publicfast.com/

**Comment by superp** [comment]
I create new user, but still can't  create new application and roles.
Application created succefully, but not shown in dashboard list and can't create new roles in this app.

**Comment by federicofdez** [comment]
Hi @superp 

I took a look into your KeyRock instance, and there seems to be an issue when serving Javascript files. Did you follow the instructions regarding the collection of static assets (here)]sudo tools/with_venv.sh python manage.py collectstatic
sudo tools/with_venv.sh python manage.py compress --force

**Comment by federicofdez** [comment]
Hi @superp 

I took a look into your KeyRock instance, and there seems to be an issue when serving Javascript files. Did you follow the instructions regarding the **collection of static assets** [here](http://fiware-idm.readthedocs.org/en/v5.2.0/setup.html#collect-static-assets)?

If not, quoting the previous link to the docs, you first need to run the following in your Horizon folder:

```
sudo tools/with_venv.sh python manage.py collectstatic
sudo tools/with_venv.sh python manage.py compress --force
```

After that, edit the `local_settings.py` file and set:

```
DEBUG = False
ALLOWED_HOSTS = [
    'your.domain.com',
    'another.domain.es'
]
SECRET_KEY = 'arandomstringhere' # DON'T LEAVE THIS SAMPLE STRING
```

The dashboard uses Javascript to load apps, and to create a modal to edit and create roles, so fixing this Javascript issue should solve your issue.

On a side note, make sure to change the idm account password from default when running KeyRock in a deployment environment. Otherwise, somebody could have admin permissions to your site!!

BR

**Comment by superp** [comment]
@federicofdez thanks for your reply.

> Did you follow the instructions regarding the collection of static assets

Yes, I have done all steps. 

```
sudo tools/with_venv.sh python manage.py collectstatic
...
0 static files copied to '/var/www/horizon/static', 951 unmodified.
sudo tools/with_venv.sh python manage.py compress --force
...
Compressing... done
Compressed 6 block(s) from 5 template(s).
```

This is my configs (only changed items):

```
DEBUG = False
ALLOWED_HOSTS = ['keyrock.publicfast.com']

LOCAL_PATH = '/tmp'
SECRET_KEY = 'XXX'

OPENSTACK_SSL_NO_VERIFY = True

DEFAULT_FROM_EMAIL = 'hello@publicfast.com'
EMAIL_URL = 'http://keyrock.publicfast.com'
EMAIL_SUBJECT_PREFIX = '[FIWARE Lab]'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'hello@publicfast.com'
EMAIL_HOST_PASSWORD = 'XXX'
```

Email don't send and js errors still present (roles not created).

**Comment by superp** [comment]
This is my Apache config: 

```
 <VirtualHost *:80>
  ServerName keyrock.publicfast.com
  ServerAdmin webmaster@openstack.org

  DocumentRoot /var/www/horizon/

  LogLevel debug

  ErrorLog /var/log/apache2/openstack_dashboard-error.log
  CustomLog /var/log/apache2/openstack_dashboard-access.log combined

  WSGIScriptReloading On
  WSGIDaemonProcess openstack_dashboard_website python-path=/var/www/horizon/openstack_dashboard:/var/www/horizon/.venv/lib/python2.7/site-packages
  WSGIProcessGroup openstack_dashboard_website
  WSGIApplicationGroup openstack_dashboard_website
  WSGIPassAuthorization On
  WSGIScriptAlias / /var/www/horizon/openstack_dashboard/wsgi/django.wsgi

  <Directory />
    Require all granted
  </Directory>

  <Directory /var/www/horizon>
    Require all granted
  </Directory>

  <Directory /var/www/horizon/openstack_dashboard/wsgi>
    Require all granted
  </Directory>

  <Location "/">
    Require all granted
  </Location>

  Alias /media/ /var/www/horizon/media/

  <Directory /var/www/horizon/media>
    Require all granted
  </Directory>

  <Location "/media">
    SetHandler None
  </Location>

  Alias /static/dashboard/fonts /var/www/horizon/openstack_dashboard/static/dashboard/fonts
  Alias /static/dashboard/img /var/www/horizon/openstack_dashboard/static/dashboard/img
  Alias /static/dashboard/css /var/www/horizon/static/dashboard/css
  Alias /static/dashboard/js /var/www/horizon/static/dashboard/js

  <Location "/static">
    SetHandler None
  </Location>
</VirtualHost>
```

**Comment by superp** [comment]
Finally it works!
I add Alias /static/ /var/www/horizon/static/ to my apache configs.

Thanks for help!

**Comment by federicofdez** [comment]
Hi @superp 

So glad to see it's working now! I'll close the issue then.

Don't forget to change `idm` account password.

Cheers!

**Comment by superp** [comment]
@federicofdez  Thanks.

I already changed my password.
But still confused with email configuration.

**Comment by federicofdez** [comment]
@superp 

We provide some guidelines to set up email in our [Production Set Up Guide](http://fiware-idm.readthedocs.org/en/v5.1.1/setup.html#email-configuration).

Come back to us if you find any trouble.
