### ISSUE TITLE
Change horizon theme

### ISSUE THREAD

**Issue by DerJayDee** [ging/fiware-idm-deprecated#67]
Is it possible to change the horizon theme in a local instance? If so: how?

[OpenStack](http://docs.openstack.org/developer/horizon/topics/customizing.html) lists that there should be an entry in the `local_settings.py` (`AVAILABLE_THEMES`) that then can get activated by collecting the static files again. But I cannot find this setting.

**Comment by federicofdez** [comment]
Hello @DerJayDee,

Thanks for writing! Themes support in Horizon is a feature that was rolled out in OpenStack Kilo release, but KeyRock's Horizon (as well as Keystone) is still based on Juno (the previous one). Therefore, I regret to say that there is currently no shortcut to be taken when changing the Horizon styles.

We might update to a newer OpenStack version in the future but, in the meantime, I'm afraid the only way to change the styles is by editing the FIWARE-Lab ones we provide along with KeyRock.

Regards,
Federico
