### ISSUE TITLE
oauth2 request  {"state": "xyz", "error": "mismatching_redirect_uri"} (HTTP 400) 

### ISSUE THREAD

**Issue by j99ht** [ging/fiware-idm-deprecated#7]
Hello,

I've been testing IDM and when I try to configure my app for login redirection, as in the example ging/oauth2-example-client, I always get the same error

"state": "xyz", "error": "mismatching_redirect_uri"} (HTTP 400) 

The request is the following

http://localhost:8000/oauth2/authorize?response_type=code&client_id=d9e8bc5cd6f6447babe774c48d993be7&state=xyz&redirect_uri=http%3A%2F%2Fwww%2Egoogle%2Ecom%2fc
allback_url

And application data

Callback URL

http://www.google.es
OAuth2 Credentials
Client ID

d9e8bc5cd6f6447babe774c48d993be7
Client Secret

a494303e16c54ab390bccbfffbccfe54

Is there anything wrong?

**Comment by vladanminic** [comment]
j99ht, you need to specify the same call back url in Application registered in your localhost:8000 as well as in config.js file

eg. for config.js
config.idmURL = 'http://localhost:8000';
config.client_id = 'be266e3af22747758b01c28f2b5be4a9';
config.client_secret = '3caaf1425ccf48cb9655d5367d306392';
config.callbackURL = 'http://localhost/login';

I was in the same position this morning :)

---

Edit: I have now different problem: Error: Unable to retrieve application.
and from time to time, horizon crash on user registration (I didn't discovered when and why) :(

**Comment by j99ht** [comment]
Thanks, I did not see the difference.
