### ISSUE TITLE
PDP properties template not compatible with Authzforce 5.4.0 and later

### ISSUE THREAD

**Issue by cdanger** [ging/fiware-idm-deprecated#71]
Hello, the current XML template for the PDP properties is no longer compatible with Authzforce 5.4.0 and later. I create a [pull request on the forked horizon repository](https://github.com/ging/horizon/pull/3) to help fix it. Let me know if this is not the right place. Thanks.

**Comment by federicofdez** [comment]
Merged! Thank you
