### ISSUE TITLE
Wrong template parameter 'role.id' in XACML policy template causing PolicyId conflict

### ISSUE THREAD

**Issue by cdanger** [ging/fiware-idm-deprecated#72]
There is a typo in PolicyId attribute in the template `access_control/policy.xacml`: `role.id` instead of `role_id`. This is causing all PolicyIds to be the same empty string in the PDP (causing Policy conflicts during evaluation). PolicyIds must be unique in XACML. I created a [pull request](https://github.com/ging/horizon/pull/2) to help fix it.

**Comment by federicofdez** [comment]
Merged! Thank you again @cdanger
