### ISSUE TITLE
"Here" reference in API specification webpage

### ISSUE THREAD

**Issue by cdanger** [ging/fiware-idm-deprecated#74]
To address the review by Apps chapter, please remove or replace link "here" in API spec page on
http://ging.github.io/fiware-idm/keyrock.html

See pull request #73 for a fix.

**Comment by federicofdez** [comment]
Merged your pull request.

Thanks!

**Comment by aalonsog** [comment]
As the file http://ging.github.io/fiware-idm/keyrock.html is imported from apiary, it shouldn't be modified here. Just for the future :)
