### ISSUE TITLE
idm-installation.sh is not working properly

### ISSUE THREAD

**Issue by raiuli** [ging/fiware-idm-deprecated#75]
After running the script I get the following errors
[log.txt](https://github.com/ging/fiware-idm/files/494209/log.txt)

Failed to start keystone_idm.service: Unit keystone_idm.service not found.
Failed to start horizon_idm.service: Unit horizon_idm.service not found.
I am using ubuntu 16.04 LTS.

**Comment by federicofdez** [comment]
Hello @raiuli 

Our installation script does not support Ubuntu 16.04 LTS yet. I'm afraid you will have to stick to Ubuntu 14 LTS in the meantime.

Regards,
