### ISSUE TITLE
user cannot be created

### ISSUE THREAD

**Issue by raiuli** [ging/fiware-idm-deprecated#77]
Hi ,

I have installed IDM using the script mentioned int the following url in Ubuntu 12.04 in 
https://github.com/ging/fiware-idm/tree/master/extras/scripts

when i am trying to signup form http://locathost:8000
i am getting following error "Error: Unable to create user, please try again later."
Any suggestion how to fixed it ???

LOG while creating test_user6

Singup user test_user6.
REQ: curl -g -i -X GET http://127.0.0.1:35357/v3/ -H "Accept: application/json" -H "User-Agent: python-keystoneclient"
RESP: [200] Vary: X-Auth-Token Content-Type: application/json Content-Length: 331 Date: Sun, 30 Oct 2016 13:36:37 GMT Connection: keep-alive 
RESP BODY: {"version": {"status": "stable", "updated": "2013-03-06T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}, {"base": "application/xml", "type": "application/vnd.openstack.identity-v3+xml"}], "id": "v3.0", "links": [{"href": "http://127.0.0.1:35357/v3/", "rel": "self"}]}}

REQ: curl -g -i -X GET http://127.0.0.1:35357/v3/domains?name=Default -H "User-Agent: python-keystoneclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}468fa8912394e77992d543032a85b72e79aab22e"
RESP: [200] Vary: X-Auth-Token Content-Type: application/json Content-Length: 320 Date: Sun, 30 Oct 2016 13:36:37 GMT Connection: keep-alive 
RESP BODY: {"domains": [{"links": {"self": "http://127.0.0.1:35357/v3/domains/default"}, "enabled": true, "description": "Owns users and tenants (i.e. projects) available on Identity API v2.", "name": "Default", "id": "default"}], "links": {"self": "http://127.0.0.1:35357/v3/domains?name=Default", "previous": null, "next": null}}

get() takes exactly 1 argument (2 given)
REQ: curl -g -i -X GET http://127.0.0.1:35357/v3/ -H "Accept: application/json" -H "User-Agent: python-keystoneclient"
RESP: [200] Vary: X-Auth-Token Content-Type: application/json Content-Length: 331 Date: Sun, 30 Oct 2016 13:36:37 GMT Connection: keep-alive 
RESP BODY: {"version": {"status": "stable", "updated": "2013-03-06T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}, {"base": "application/xml", "type": "application/vnd.openstack.identity-v3+xml"}], "id": "v3.0", "links": [{"href": "http://127.0.0.1:35357/v3/", "rel": "self"}]}}

REQ: curl -g -i -X GET http://127.0.0.1:35357/v3/role_assignments?role.id=7769546756924cf6b4d9f3a102faca1f&scope.domain.id=default -H "User-Agent: python-keystoneclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}468fa8912394e77992d543032a85b72e79aab22e"
RESP: [200] Vary: X-Auth-Token Content-Type: application/json Content-Length: 426 Date: Sun, 30 Oct 2016 13:36:37 GMT Connection: keep-alive 
RESP BODY: {"role_assignments": [{"scope": {"domain": {"id": "default"}}, "role": {"id": "7769546756924cf6b4d9f3a102faca1f"}, "user": {"id": "raiuli"}, "links": {"assignment": "http://127.0.0.1:35357/v3/domains/default/users/raiuli/roles/7769546756924cf6b4d9f3a102faca1f"}}], "links": {"self": "http://127.0.0.1:35357/v3/role_assignments?role.id=7769546756924cf6b4d9f3a102faca1f&scope.domain.id=default", "previous": null, "next": null}}

---

Some update  in /horizon/openstack_dashboard/fiware_api/keystone.py at line 243.
 new_user = keystone.users.update(new_user, password_changed_at=date)

This line is causing problem and giving following error
"get() takes exactly 1 argument (2 given)"

But if i am commenting the line the user creation works.

Please suggest if that will be ok to comment the line.

---

**Comment by federicofdez** [comment]
Dear @raiuli,

Thank you very much for reporting this issue. After taking a deep look into it, it turns out that there was indeed some sort of error that was not being correctly handled. I just made some fixes (ging/horizon@69115cd1c6bbf57600086c3325a53cffe547484b) so that it works properly. Of course, commenting that line is not required any more.

Everything should work as expected now, but please write back if you still run into any other issue.

Thank you very much and sorry for the inconvenience this may have caused you!

Sincerely,
Federico Fernández
