### ISSUE TITLE
App authorization error - exceeded the limit of column state(CHAR(256))

### ISSUE THREAD

**Issue by vladanminic** [ging/fiware-idm-deprecated#8]
Dear ging team,

I'm using PPnet (Social Network SE). I Registered the app on the Fi-LAB to accept authorization but when I tried to login I got this error:

String length exceeded.The length of string '{"client_id":"1b881b8277084b2ea1b5f1787970e44f","network":"fiware","display":"popup","callback":"_hellojs_aeziej0n","state":"","oauth_proxy":"https://auth-server.herokuapp.com/proxy","scope":["basic"],"oauth":{"version":2,"auth":"https://account.lab.fiware.org/oauth2/authorize","grant":"https://account.lab.fiware.org/oauth2/access_token"}}' exceeded the limit of column state(CHAR(256)). (HTTP 400)

It "smells" like DB error, but I'm not sure.

Thank you!

Best regards,
Vladan

**Comment by vladanminic** [comment]
Error was in PPnet URL generator. In this file https://raw.githubusercontent.com/pixelpark/ppnet/master/www/scripts/vendor-07c80755.js
line 85101 needs to be commented. I also commented few more lines in order to get the same URL request as in OAuth2 example.

**Comment by garcianavalon** [comment]
Dear Vladan,

I understand you are trying to log in a user from your application using the OAuth2.0 protocol, correct me if I am wrong.

The error you are seeing is clearly a DB error, as the value for 'state' is too long. It seems that the oauth2 provider is understanding that whole json as the 'state' variable. Are you sending that on purpose? If so, please reduce it to fit the 256 char length. If this is not the case and you don't intend to save all of that information, I need more details of the request you are making to the server (endpoint, headers, body, etc.), to see if its an error on the request or on the server side.

Best regards.

**Comment by vladanminic** [comment]
Dear Garsia,

I tried to login on PPnet (Social Network SE) using KeyRock IDM. PPnet was litle bit outdated, so I got help from them and we managed to solve the problem by commenting line for "oauth_proxy" and "grant"

Thank you!

**Comment by michelevolpe** [comment]
Hi Vladan,
same problem as you were experiencing ....  String length exceeded...
Could you please elaborate a little bit about commenting line for "oauth_proxy" e "grant" ?

Thanks
 Michele
