### ISSUE TITLE
Integrate keyrock in a app

### ISSUE THREAD

**Issue by ManuelAlfonso** [ging/fiware-idm-deprecated#83]
Hello,

I have to integrate keyrock in a app. So I have installed keyrock in my computer but now I don't know what is the next step.

The thing is that I beginner in all it. 4 days ago, I didn't know anything about it. about Fiware and also keyrock. But I have readed a lot papers, and now I know more about it. but so, I don't know enough. If somebody could help me.

I want integrate keyrock Fiware in a app. But I don't know how, and I don't know what are the next steps.

Thank you so much

**Comment by aalonsog** [comment]
Hi, this channel is used for reporting issues. For questions regarding the GE use you should use the specific help channels of FIWARE.
