### ISSUE TITLE
Error: Unable to retrieve application.

### ISSUE THREAD

**Issue by vladanminic** [ging/fiware-idm-deprecated#9]
Dear ging team,

I installed keystone/horizon on my VM instance on Fi-LAB .
I registered new App (got Client ID and Client Secret), but when try to access it I got message.
Error: Unable to retrieve application.

When I do the same (with same code) directly on Fi-Lab, I can retrieve App.
Can you please how to solve the problem.

Thank you!

Best regards,
Vladan

**Comment by DiegoAlfonso2** [comment]
How did you fix it? I'm facing the same problem. I'm trying to install RSS, which authenticates against IDM. Thank you!

**Comment by federicofdez** [comment]
Hi @DiegoAlfonso2,

Thanks for writing. Could you please provide us a little more information about your issue? Are you using your own KeyRock on a VM instance on FIWARE Lab or are you using FIWARE Lab directly?

**Comment by federicofdez** [comment]
Seems to be solved! Feel free to write back otherwise.

Cheers!
